apiVersion: v1
kind: Namespace
metadata:
  name: advancedchatbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advancedchatbot
  namespace: advancedchatbot
  labels:
    app: advancedchatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advancedchatbot
  template:
    metadata:
      labels:
        app: advancedchatbot
    spec:
      containers:
        - name: advancedchatbot
          image: akanuchiacr.azurecr.io/advancedchatbot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SESSION_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: OPENAI_API_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20   # give FastAPI more time to start
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
      imagePullSecrets:
        - name: acr-pull-secret
