apiVersion: v1
kind: Service
metadata:
  name: advancedchatbot-svc
  namespace: advancedchatbot
spec:
  type: LoadBalancer
  selector:
    app: advancedchatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
