apiVersion: v1
kind: Service
metadata:
  name: advancedchatbot-service
  namespace: advancedchatbot
spec:
  selector:
    app: advancedchatbot
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
