apiVersion: v1
kind: Service
metadata:
  name: pdf-db-assistant-svc
spec:
  selector:
    app: pdf-db-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
