apiVersion: v1
kind: Service
metadata:
  name: pdf-chat-assistant-service
spec:
  selector:
    app: pdf-chat-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
