apiVersion: v1
kind: Service
metadata:
  name: pdf-db-assistant-svc
  namespace: advancedchatbot
spec:
  selector:
    app: advancedchatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
